language: cpp

sudo: false

compiler:
  # - clang
  - gcc

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libboost1.55-all-dev
      - liblua5.1-0-dev
      - lua5.1
      - luarocks
      - rubygems

cache:
  - apt

before_script:
  - luarocks --local install busted
  - gem install cucumber

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - make -C Build/linux/gmake config=release_x64
  - bin/linux/gmake/x64/Release/cucumber_example > /dev/null & cucumber
  - ~/.luarocks/bin/busted
