language: cpp

compiler:
  - clang
  - gcc

before_install:
 # - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo add-apt-repository  --yes "ppa:codegear/release"
 - sudo apt-get update -qq
 - sudo apt-get -qq --yes install premake4
 # - sudo apt-get -qq --yes install boost1.55
 - sudo apt-get -qq --yes install libboost-all-dev
 - sudo apt-get --yes install lua5.1 luarocks
 - sudo luarocks install luafilesystem
 - sudo luarocks install penlight
 - gem install cucumber #ruby assumed to be installed

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - premake4 prepare
  - make -C Build/linux/gmake config=release64
  - premake4 cucumber
